"""Planning agent using instructor library"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06_AusieScrap.ipynb.

# %% auto 0
__all__ = ['topics_url', 'results', 'get_topics', 'get_license_types', 'search_results', 'get_area_id']

# %% ../../nbs/06_AusieScrap.ipynb 4
import requests


# %% ../../nbs/06_AusieScrap.ipynb 5
topics_url = "https://verify.licence.nsw.gov.au/publicregisterapi/api/v1/licence/search"

# %% ../../nbs/06_AusieScrap.ipynb 6
def get_topics():
    response_topics = requests.get(topics_url)
    topics_list = response_topics.json()['PageConfig']['homePageConfig']['topics']['topics']
    return topics_list

#| hide

# %% ../../nbs/06_AusieScrap.ipynb 9
def get_license_types(topic:str):
    license_types_url = "https://verify.licence.nsw.gov.au/publicregisterapi/api/v1/licence/search/getlicencetypes"
    data = {"filters":[{"type":"topic","params":{"topic":topic},"options":{"autocomplete":False}}],"sorting":[{"type":"relevanceScore","order":-1}],"paging":{"pageNumber":0,"pageSize":200}}
    response_license_types = requests.post(license_types_url, json=data)
    license_types_list = response_license_types.json()
    return license_types_list

#| hide

# %% ../../nbs/06_AusieScrap.ipynb 12
def search_results(topic:str, license:str, suburb:str):
    url_search = "https://verify.licence.nsw.gov.au/publicregisterapi/api/v1/licence/search/query"
    data={"filters":[{"type":"topic","params":{"topic":topic},"options":{"autocomplete":False}},{"type":"licenceType","params":{"licenceType":[license]},"options":{"autocomplete":False}},{"type":"area","params":{"areaSearchTerm":suburb},"options":{"autocomplete":False}}],"sorting":[{"type":"relevanceScore","order":-1}],"paging":{"pageNumber":0,"pageSize":200}}
    resp_search = requests.post(url_search, json=data)
    return resp_search.json()

results = search_results("ADL", "Asbestos Removal Licence", "Abbotsbury")

# %% ../../nbs/06_AusieScrap.ipynb 18
def get_area_id(area:str):
    areas_url = "https://verify.licence.nsw.gov.au/publicregisterapi/api/v1/licence/search/getareas"
    data = {"filters":[{"type":"topic","params":{"topic":"ADL"},"options":{"autocomplete":False}},{"type":"area","params":{"areaSearchTerm":area},"options":{"autocomplete":True}},{"type":"licenceType","params":{"licenceType":["Asbestos Removal Licence"]},"options":{"autocomplete":False}}],"sorting":[{"type":"relevanceScore","order":-1}],"paging":{"pageNumber":0,"pageSize":200}}
    resp_areas = requests.post(areas_url, json=data)
    areas = resp_areas.json()
    return areas[0]['locationId'] if areas else None

get_area_id("Abbotsbury")

