"""Planning agent using instructor library"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_planning_agent copy.ipynb.

# %% auto 0
__all__ = ['TaskGraph']

# %% ../../nbs/03_planning_agent copy.ipynb 4
from pydantic import BaseModel
from typing import List, Dict

class TaskGraph(BaseModel):
    """A graph of tasks and their dependencies"""
    tasks: List[str]
    dependencies: Dict[str, List[str]]

