"""Agent that get the prices of properties in a given location and size"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/07_Precios.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/07_Precios.ipynb 4
import requests

