"""Planning agent using instructor library"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_RealtimeSTT.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/05_RealtimeSTT.ipynb 4
#| eval: false
#| eval: false
from RealtimeSTT import AudioToTextRecorder


if __name__ == '__main__':
    recorder = AudioToTextRecorder()
    recorder.start()
    input("Press Enter to stop recording...")
    recorder.stop()
    print("Transcription: ", recorder.text())

# %% ../../nbs/05_RealtimeSTT.ipynb 6
#| eval: false
import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer
import soundfile as sf

