"""Planning agent using instructor library"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_tts.parler.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/04_tts.parler.ipynb 4
import torch
from parler_tts import ParlerTTSForConditionalGeneration
from transformers import AutoTokenizer
import soundfile as sf

